general:
  cities:
    - Tel Aviv
    - Jerusalem
    - Haifa
    - Beersheba
    - Eilat



local_save:
  folder_name: weather_data

s3:
  bucket_name: weather-data-aws
  raw_prefix: raw-data
  processed_prefix: processed-data
  summaries_prefix: summaries

api:
  base_url: http://api.openweathermap.org

#spark:
#  app_name: WeatherETL
#  master: local[*]
