general:
#  A list of cities for which weather data will be fetched from the API.
  cities:
    - Tel Aviv
    - Jerusalem
    - Haifa
    - Eilat

local_save:
#  The local directory where raw weather data will be saved.
  data_folder_name: weather_data
#  The local directory where processed results and output files will be stored.
  output_folder_name: outputs

s3:
#  The name of the AWS S3 bucket used to store all weather data.
  bucket_name: weather-data-aws
#  Folder path (prefix) in S3 where raw weather data is stored.
  raw_prefix: raw-data
#  Folder path (prefix) in S3 for storing cleaned or transformed weather data.
  processed_prefix: processed-data
#  Folder path (prefix) in S3 for storing dashboard, summaries and reports.
  summaries_prefix: summaries

api:
#  The base URL of the weather API (OpenWeatherMap) used to retrieve current weather data.
  base_url: http://api.openweathermap.org
